### ISSUE TITLE
simulating the second controller track-pad

### ISSUE THREAD

**Issue by belger-dussen** [polygraphene/ALVR#102]
I want to use GoogleEarth VR and for this it requires a second controller. Is there a way for this?
I'm currently using v2.2.1-alpha and tried FreePIE but could not find any available buttons for this.

**Comment by pcky** [comment]
@polygraphene Generally, a second controller implemented in the ALVR FreePIE API would be awesome! Otherwise, i'm not sure how to simulate the second track pad within ALVR. Thanks!

**Comment by vrokolos** [comment]
I believe the Gear VR and oculus Go doesn't support a second controller. If you were to be able to connect it somehow to the host PC it might work if FreePIE adds support for it.

But is it worth it really? Instead of buying a second controller to only use with ALVR why not think about getting 2 PS Moves and 2 PS Eye cameras on ebay? They're pretty cheap and they have far superior tracking than the gear vr controller. And they are fully supported.

**Comment by polygraphene** [comment]
Does GoogleEarth require two controller?
I can play it with single controller.

I like the idea of second controller for FreePIE. I will add this feature.

**Comment by pcky** [comment]
> Does GoogleEarth require two controller?

Yes, with the second controller's track pad your can tilt the globe. That way you can control if you stand on top of the earth or if you have it in front of you. My current workaround is to play one of the tutorials any cancel it once it took the desired tilt angle that i wish to continue with.
