### ISSUE TITLE
How do I test USB tethering?

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#135]
I'm trying to test it with USB but I cannot figure out how to enable USB tethering on the Gear VR. What are the steps?

Currently I'm doing this: Connect phone to USB -> settings -> enable USB Tethering. Try to disconnect USB and insert the phone into gear vr, then connect USB into gear vr. USB tethering gone.

Is there another way?

**Comment by Tux0Topo** [comment]
@vrokolos Hi!! You can´t. There is NO WAY to enable usb tethering with gearvr. From the moment that you unplug the usb cable from the phone, the thethering is gone.
Depending on your phone, you can plug some usb to ethernet adapter to the gearvr, and that way you could gain tethering... That implementation was commented in the riftcat reddit and forums...

**Comment by polygraphene** [comment]
As Tux0Topo said, Gear VR HMD forces the phone into USB host mode. So you need to use USB ethernet adapter.
It was a mistake that I said support tethering. Tethering is not supported on all devices including Go.
Sorry.

**Comment by vrokolos** [comment]
Ah it's ok. Still, I'll try to create a tasker task that enables usb tethering and maybe run it through the phonecast app when I have some free time.

**Comment by axemation** [comment]
Hi, really interested in trying usb tethering with GearVr,. So far I've tried making my phone a mobile hotspot while turning 4g off and although this works it is very laggy with lots of the unrendered black area being seen. I've also tried using a usb c to ethernet adapter from gear vr port running ethernet cable to laptop, the laptop recognizes the ethernet connection but when I go into phonecast into the settings options, the tethering folder is blocked saying that phonecast is unable to run this. I wonder if there is an app you could use as a workaround to enable usb tethering?

**Comment by Spyindabox** [comment]
I know this is an old thread but its still open and I figured it out. Just plug usb cord into phone (if you can fit it into headset) and then into computer. From there launch usb tethering and put gearvr into dev mode by going to settings then apps then manage storage then click version number 5 times enable dev mode. From there enable usb tethering. Also in reply to axemation you would require root access to enable usb tethering if blocked. If you have root just use something like https://play.google.com/store/apps/details?id=it.barbaro.aut&hl=en_US

**Comment by ergo** [comment]
So @polygraphene and @Spyindabox I also managed to get working USB thethering with ALVR inside Oculus app. I created a signed hello world and it worked for me. Finally had fluid stable image (I own an N router and it is not capable of delivering wifi speed needed).
However if I plug USB via Gear VR the option to enable usb tethering is not selectable, did you manage to get around this @Spyindabox? I don't have a good idea on how to fit my phone (s9) with cable connected directly to it into Gear headset.

**Comment by ayhamo** [comment]
@ergo hey, i wish to know what u did to get it working
what is "signed hello word"?
Thnaks

**Comment by Spyindabox** [comment]
@ergo I was talking about just using developer mode to launch apps like alvr and then just plugging the phone directly into computer without using the gear vr. If you cant do this because your phone cant fit, then you might consider starting a 5ghz network from your phone something like "NetShare -no root tethering wifi router" (thats a paid app but there are free ways to do it) and then connecting your computer directly to the hotspot I can confirm that this method works. If you use netshare with (https://forum.xda-developers.com/galaxy-s3/themes-apps/app-wifi-band-switcher-switch-2-4ghz-5-t1891970) a wifi band switcher, (that  requires root) you can broadcast in 5ghz band. You can probably just use something like netshare without the wifi switcher app but you need to make sure its using 5ghz as in my testing it could be inconsistent without the wifi band switcher. If you can get it set up right this would be probably faster than a router as its a direct connection between the computer and phone. Hope this helps

**Comment by Spyindabox** [comment]
@ergo  I wanted to add that using Gear VR developer mode, and doing what you were talking about by plugging phone into gearvr and then connecting gear vr into computer, I was able to get it to almost connect but kept getting (usb device not recognized with device descriptor errors), It could be something with just my computer but I think the gearvr pollutes the connection somehow. It didn't seem to be charging either. 

You also might consider switching to a bobo vr z4 (they're pretty cheap) and have a big side area for the wire to hang out as the phone clamp is vertical rather than horizontal. AThen just launching alvr via dev mode and have the phone plugged directly into the computer for usb tethering. This would help with charging as well, alvr and other gear vr apps drains the battery super fast on my galaxy s6. Although I would note the bobovr z4 just barely lets in light through the top of the screen which can be covered up with tape or something.

**Comment by ergo** [comment]
I also bought USB C -> ethernet dongle (https://i-tec.cz/en/produkt/c31metalglan-2/ this one) in the end, and everything is working like a charm via Gear VR.
