### ISSUE TITLE
H.265 HEVC 

### ISSUE THREAD

**Issue by fdinsdale** [polygraphene/ALVR#139]
Hi,
I am using v2.1.5 and its working nicely with xplane11, bigscreen, elite dangerous, altspace and virtual desktop so far.
My question is will the codec H.265 in the alpha improve on resolution or refresh quality? 
My gpu is a x1060 and the router has 5g ac. 
H.265 is generally supporting 4k resolution correct?

Thanks

**Comment by crimson-woof** [comment]
Sorry to burst your bubble, but H.265 won't be a huge improvement in quality.  It is more efficient at encoding meaning that it will use less bandwidth to achieve the same quality at much higher resolution than required for Gear VR.  The maximum resolution of your device is less than 4k.  It will help people with low performing networks use less bandwidth.

Rather than wait for H.265, make sure you are using the correct per eye resolution setting in SteamVR > Settings to match what you have set on your ALVR server.

**Comment by fdinsdale** [comment]
Thanks for the info.
I'm currently using the 2560x1440 resolution on the alvr server because its looks better than the recommended  and my wifi can handle the bandwidth.
 I think i'll try the 3072x1536  alvr setting with 1536x1536 in stream vr  and see if I can squeeze a little more sharpness.

**Comment by Woohaaa** [comment]
2560X1440? There is 2880X 1440 in ALVR setting,not this resolution.

**Comment by fdinsdale** [comment]
You're right, my typo.  
Anyway I was trying the 3072x1536 with matched resolution in steam vr last night and the results were good. The image was a little sharper and i didn't notice any issues with the streaming quality.

I have also been toggling the "allow asynchronous reprojection" and "enable advanced supersample filtering" but have not really noticed any differences in quality one way or another.
