### ISSUE TITLE
Force 60 fps on the GO

### ISSUE THREAD

**Issue by penkamaster** [polygraphene/ALVR#156]
In previous version where the 72 fps was not implemented I was having better headtracking.

Can we have a option to force 60 fps. 

Thank you.

**Comment by polygraphene** [comment]
I don't think 72fps cause bad headtracking.
Newer version contains many improvement or fix as well as 72fps support.
I want to know the exact cause of the issue before implement that feature.

**Comment by gigabulloba** [comment]
Same issue here. Head tracking is fine. The game rendered on my monitor is nice and smooth, but character movement etc. in the headset is jerky. It looks almost like the game is running sub 30 fps, although I suspect it's something with the encoding.

@penkamaster 
Thanks. I downloaded your build from the other thread and it's a night and day difference with the forced 60 fps version.  Movement is much less choppy now. It's a huge improvement.

**Comment by penkamaster** [comment]
Hi Polygraphene, 
I've changed "-fps 60" to "-fps 72" on https://github.com/polygraphene/ALVR/blob/master/ALVR/ServerConfig.cs#L144
and build ALVR (not the driver),
and the 60 fps version keeps working better.

**Comment by saintkamus** [comment]
@penkamaster Headtracking was never the problem. But your build completely fixes the in game FPS  issue that was present in ALVR since I started using it!

I believe the issue is that the nVidia hardware is incapable of encoding at more than 60 FPS in real time (regardless of resolution)

While doing offline encoding, we know that it can go much higher than 60 FPS, but real time encoding is a whole different beast, and it's simply not designed to go higher than 60Hz.

**Comment by timorsohc** [comment]
👍 Yes! ALVR run so smooth now in my Oculus Go; with @penkamaster 60fps version. Amazing! 👍 

I wish @polygraphene would update the official client version in the Oculus store apps with this minor correction (maybe as 2.3.1?). 
Since my kids play with this Oculus Go recently, and they not too familiar with run sideload apps via "unknown resource" folder :)

**Comment by drowhunter** [comment]
where is the link to penkamaster 60fps version?

**Comment by cmtec** [comment]
@drowhunter https://github.com/polygraphene/ALVR/issues/116

**Comment by polygraphene** [comment]
I have not yet done 60Hz version, but I found a terrible flaw about 72Hz support.
Client v2.3.1 may mitigate the issue.

**Comment by cmtec** [comment]
Microstutter is still present in v2.3.1 (At least for me running Elite Dangerous)

**Comment by cmtec** [comment]
Here you go:
[logcat.txt](https://github.com/polygraphene/ALVR/files/2443133/logcat.txt)

**Comment by cmtec** [comment]
@penkamaster : I might have been wrong to say v2.3.1 not solving the core issue. After some more investigation I have concluded that now when running 72fps it might be the GPU/driver (or maybe even steamvr version combination) that makes the stutter. However i would like to have an option to force ALVR to 60fps to ease the strain on the GPU.
