### ISSUE TITLE
How to optimize experience through Internet

### ISSUE THREAD

**Issue by liyiiamh** [polygraphene/ALVR#159]
Hi, thanks for your great APP.
It works very well through WiFi but we have bad experience on Internet by adding a public IP to broadcast list.
We tried to reduce the bitrate to 3M and raise buffer to 2000kB but still many mosaics on the screen.
How can we do to optimize it? Use RTP?
Thanks very much~

**Comment by liyiiamh** [comment]
Hi, we upgrade app to the latest version today and the performance is improved a lot. Thank you.
The latency is a little bit long, about 200ms. And the packet loss is about 20 per second.

**Comment by polygraphene** [comment]
Latest version contains FEC support which recovers lost packet. So the upgrade might improve the performance.

I think RTP does not improve performance because RTP does not contains any performance feature in itself. We need to implement some encoding(reordering)/retransmission function by ourselves besides RTP. And we already have FEC as encoding. Retransmission is not suitable for our low latency situation.

Note that our protocol have no encryption or authentication, so please be careful on security.
I recommend to use VPN on the internet.
