### ISSUE TITLE
Crackling audio on Oculus Go

### ISSUE THREAD

**Issue by gigabulloba** [polygraphene/ALVR#168]
When streaming audio to my Oculus Go from ALVR it is very distorted.

**Comment by polygraphene** [comment]
If you are using 2.4GHz Wi-Fi, try 5GHz.
And please tell me packet loss rate.

**Comment by gigabulloba** [comment]
I'm using 5GHz.  I'm sitting right beside my router and I can push the video bitrate up beyond 100 mbps before I start to see artifacts. It's not my wifi. The packet loss rate is zero.

**Comment by timorsohc** [comment]
@gigabulloba 
I had the same problem couple weeks ago. But after test with DPC latency test I found that my soundcard run in very-high DPC latency (since it originally come from Microsoft ~ Windows 10 Generic HD audio driver). After I updated it with proper soundcard driver and then everything run so well. The streaming audio now is prefect! :)

Please check your PC DPC latency, since it would affected with your audio/multimedia function (decode and encode).

**Comment by gigabulloba** [comment]
Sadly, Asus has no newer drivers for my onboard sound.  However, I was able to get it working by mirroring  the audio from a USB headset instead.

**Comment by schwendigo** [comment]
is there any way to disable streaming audio (to save bandwidth)? the audio to my gearVR is very distorted - i can just plug headphones into my PC.

also, i am using a behringer external USB auto interface @ 192k , perhaps that is it.

**Comment by nk33** [comment]
> 
> 
> is there any way to disable streaming audio (to save bandwidth)? the audio to my gearVR is very distorted - i can just plug headphones into my PC.
> 
> also, i am using a behringer external USB auto interface @ 192k , perhaps that is it.

just turn the volume down on the headset and the audio up on the pc speakers/headphones lol - alvr plays audio from both but you can turn your quest/go down
