### ISSUE TITLE
The ArCore-based position isn't accounting for neck motion

### ISSUE THREAD

**Issue by sigmaxipi** [polygraphene/ALVR#175]
If I'm sitting in a chair and pitch my head upwards, ArCore will report an increase in the y direction. This increase is based on the position of the camera, but it should actually be based on the position of your eyes. The camera translates more than your eyes when you rotate your neck This causes the view to slide around more than it should.

If I cover the camera, have my head just above the virtual floor and tilt up/down, there is a slight bit of simulated motion. But If I have the camera exposed, there is a lot of motion and I end up moving through the floor.

I think the fix is something like:
```cameraPosXYZ = ArThread.getPosition()
rotXYZW = ArThread.getOrentation()
vec3 baseCameraToEyeOffset = <0, 0, cameraToEyeDistance> // vector in the +Z
vec3 cameraToEyeOffset = rotXYZW * baseCameraToEyeOffset
eyePosXYZ = cameraPosXYZ - cameraToEyeOffset
Other_Tracking_Source_Position = eyePosXYZ```

**Comment by polygraphene** [comment]
Thank you for reporting.
I will check it. Please be patient.

**Comment by dpluigi** [comment]
Any update.  I experience the same thing.  It is especially noticeable since in the VR view, there is an uinstrument panel in front of me.  The program I am using a soaring flight simulator, and typically you are in a small cockpit.

It is also noticeable that the view camera scaling in passthrough mode seems off.  Of course depth perception is flat with one eye view vs stereo view.

Thank you for keeping us updated.
Donat
