### ISSUE TITLE
ALVR server crash

### ISSUE THREAD

**Issue by MirraLee** [polygraphene/ALVR#176]
Hi

Oculus Go connected to Steam, and the below message appears and the ALVR server crashes

NvEnc NvEncoderD3D11 failed. Code=2 NvEncoder::NvEncoder : m_nvenc.nvEncOpenEncodeSessionEx(&encodeSessionExParams, &hEncoder) returned error 2 at c:\src\alvr\alvr_server\nvencoder.cpp:51

Thanks

**Comment by polygraphene** [comment]
What GPU are you using?
Code=2 means NV_ENC_ERR_UNSUPPORTED_DEVICE. So your GPU seems not support NVENC.

**Comment by MirraLee** [comment]
I had to manually disable the on-board Intel HD Graphics although by looking at the attached txt files it still is there and the P4000 is not there.

Is the P4000 not good enough?

[cid:image001.png@01D4348B.E74E64C0]



Mirra L. Maheden, CP | VPD Lead
7629 Wagner Road, Edmonton AB T6E 5B2
T: +1 587-337-0337  E: mmaheden@TransEdLRT.com<mailto:mmaheden@TransEdLRT.com>

**Comment by polygraphene** [comment]
Quadro P4000 should work because it supports NVENC.
ALVR maybe try to use Intel graphic.

Can you send me the driver.log file?
Instruction is [here](https://github.com/polygraphene/ALVR/wiki/Debugging#how-to-enable-server-driver-log-output)

**Comment by MirraLee** [comment]
Hi

See attached

Just for your info, the end product I am looking for is to have a user walk around in the exe file that these two applications output

https://enscape3d.com/knowledgebase/using-virtual-reality-headset/

https://irisvr.com/

https://assets.irisvr.com/assets/videos/MR_Splash_Video.6d94826af3ae92b3bc7c60e85676e37e.mp4


Typically in the past I have used the Oculus Rift and the Vive but the company I am with now corporately has chosen to go with the Oculus Go, and I found your application as a great tool to get this working.

Mirra





Mirra L. Maheden, CP | VPD Lead
7629 Wagner Road, Edmonton AB T6E 5B2
T: +1 587-337-0337  E: mmaheden@TransEdLRT.com<mailto:mmaheden@TransEdLRT.com>

**Comment by EdWata** [comment]
Hello! I have the same error,
i have a Geforce GT 740M, I'm pretty sure that it is compatible but i get the same error:

Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=2 NvEncoder::NvEncoder : m_nvenc.nvEncOpenEncodeSessionEx(&encodeSessionExParams, &hEncoder) returned error 2 at c:\src\alvr\alvr_server\nvencoder.cpp:51

This is the log file:
[driver.log](https://github.com/polygraphene/ALVR/files/2825911/driver.log)

But I think the problem is that I have an intel integrated card, but I don't know how to change which GPU uses the ALVR.

Thanks for your attention.
