### ISSUE TITLE
assetto corsa

### ISSUE THREAD

**Issue by newflavour** [polygraphene/ALVR#191]
has anyone successfully run Assetto (from steam) in VR using ALVR?

**Comment by akslan** [comment]
I have, it has been very trouble free for me. What kind of issues are you having?

**Comment by akslan** [comment]
If your issue is that you can't see the menus in your headset, that is because of the way Assetto Corsa is made. The menus are just a launcher that configures the game and then the game actually starts to run when you click drive. You should start to see the game in your headset once you are in the pits ready to drive off. If you have chosen Openvr as your rendering mode that is.

**Comment by akslan** [comment]
This source might help you set it up correctly.
https://www.racedepartment.com/downloads/assetto-corsa-vr-guide.19037/

**Comment by newflavour** [comment]
it was the openVR part that got me. thanks.
I'll close this now.
