### ISSUE TITLE
Feature Request: ALVR for OS X

### ISSUE THREAD

**Issue by pjpalomaki** [polygraphene/ALVR#192]
Now, I know nothing about the underlying frameworks that ALVR is running on, but I would pay money to get ALVR working on OS X.

We do a lot of development and animation work on OS X specifically for Oculus GO. While Adobe Premiere Pro and After Effects support SteamVR on OS X, there is no way to preview your work on the GO. ALVR would be the perfect solution for this - lightweight headset and wireless connectivity. Great for prototyping etc.

What would it take to make ALVR run on OS X?

Thanks.

**Comment by polygraphene** [comment]
That's an interesting idea.

I have no plan to port ALVR on another platform now.
But if I will do, it will be hard work to me, because I have no programming experience in OS X.

It requires a lot of work like followings.

1. Support Metal (or OpenGL?) texture: Get layers from OpenVR and compose (alpha blending) it by Metal API.
2. Use hardware encoder: Convert composed texture into proper format, and send it to encoder API.
3. Port miscellaneous parts: Sound capturing, socket communication, GUI, and so on.

It will rewrite a large part of current code base.
If someone want to port it to OS X, I can help. But now I have no skill and time to implement it by myself.

**Comment by ManLikeDuck** [comment]
Poly, im running mac os and would love to see ALVR for mac, if I could be of any help i could try and help u, just let me know!

**Comment by Pepeeze** [comment]
One more for an OS X Port! I would absolutely love to see it come to light!

**Comment by MacMerc** [comment]
A Mac port would be amazing.  Also, you can use SoundFlower to stream the audio as many other programs do.  There is a GitHub release of it.

**Comment by ohld** [comment]
Hi! 13 of my friends want this tool to be used with Oculus Go/Quest + `mac OS`. How can we compile client to mac OS?

**Comment by sreenadhdevs** [comment]
any news on alvr server for mac?

**Comment by jjalonso** [comment]
me too

**Comment by griffinmalone** [comment]
Just another request. Would happily pay/donate for the service, as I'm sure many others would. Have a Mac pro and half od steam vr games would run fine on it and I would love to get them on my quest.
