### ISSUE TITLE
No error,Firewall ported and still no connection :^{

### ISSUE THREAD

**Issue by danslade** [polygraphene/ALVR#207]
Hey just got my Oculus Go and I want to try skyrim vr with a gamepad. Unfortunately I cant connect. First it was my drivers could connect for a second but then it would fail I updated but to no prevail. Then I ported my firewall and made sure I was on h264 but still nothing.
I'm running a GTX 760 and version 2.3.1. Any help out there?
Should I download v 2.1.5 like the other user listed here?
Thank!

**Comment by polygraphene** [comment]
Are you stuck on "Headset not found"?
If so, please confirm the firewall rule is enabled on all (private and public) profiles and UDP/9944.

And please try "ping (Go's IP address)" command on command prompt.

If you can use adb, you can try v2.1.5. But I don't think the issue is caused by newer version.

If you stuck on "Server is down", I want to see driver.log file.
See: https://github.com/polygraphene/ALVR/wiki/Debugging#how-to-enable-server-driver-log-output

**Comment by ironmanxiv** [comment]
hey I'm interested because I have the same problem but I don't know how to confirm the firewall rule is enabled on all (private and public) profiles and UDP/9944. on a windows 10 computer I would like to know ASAP thank you
