### ISSUE TITLE
Can I connect my Oculus Go to my PC through a LAN adapter?

### ISSUE THREAD

**Issue by Kbeam007** [polygraphene/ALVR#211]
I have tried connecting my Oculus Go to my PC with wireless, but it's to laggy, with artefacts and skips frames a lot. I was wondering, is it possible to connect my PC to the Oculus Go to my PC with one of those adapters https://www.aliexpress.com/item/COTS-Hot-Micro-USB-5-Pin-10-100-Mbps-RJ45-LAN-Ethernet-Adapter-for-Tablet-PC/32749210798.html?spm=a2g0s.9042311.0.0.71214c4dqAoQIW and stream with that wired connection.

**Comment by Tux0Topo** [comment]
I wouldnt choose that adapter. Look for a 1000mbps ones.
Consider that the common usb port support 480mbps, and the minimun recommended wifi connection N supports 300mbps. Using cable, always will reduce latency which is a good thing, but the extra speed is also a need.

**Comment by Colonel-Izzi** [comment]
We've found over on the [Go sub](https://www.reddit.com/r/OculusGo/comments/8ure0x/oculus_go_connected_with_rj45_cable_seems_to_work/e2j1cog/) that a lot of the USB to **Gigabit** Ethernet adapters use the Realtek RTL8153 controller, which isn't recognized by stock Android 7.1.2 systems (which includes the Go).  Luckily though a 10/100 adapter typically still provides enough bandwidth for a high resolution 60fps h.265 stream. 
 
(haven't tested with h.264)

**Comment by Kbeam007** [comment]
> 
> 
> We've found over on the [Go sub](https://www.reddit.com/r/OculusGo/comments/8ure0x/oculus_go_connected_with_rj45_cable_seems_to_work/e2j1cog/) that a lot of the USB to **Gigabit** Ethernet adapters use the Realtek RTL8153 controller, which isn't recognized by stock Android 7.1.2 systems (which includes the Go). Luckily though a 10/100 adapter typically still provides enough bandwidth for a high resolution 60fps h.265 stream.
> 
> (haven't tested with h.264)

My question was rather on the software side: Would ALVR recognise an Oculus Go connected to a PC with a lan cable instead of only through WiFi. I don't even know whether the Oculus Go would recognise the wired link...

**Comment by Colonel-Izzi** [comment]
I was actually really replying to Tux0Topo there because he told you to get a Gigabit adapter which if you just go and buy whatever you can find has a higher chance of not working.   I guess I should have made that more clear.
  
But yes this will work with ALVR.  I've tried it myself.  The Go doesn't have an Ethernet configuration panel but these adapters work by default in DHCP mode.  So assuming your router is configured for DHCP, which it almost certainly is, you just need to disable your Go's WiFi connection, plug the adapter in (either directly if you get a Micro USB adapter, or via a Micro USB OTG adapter if you get a Type A adapter), hook up the Ethernet cable, and then proceed as you normally would.

**Comment by Kbeam007** [comment]
I was actually planning of hooking the Oculus Go directly to my Laptop when travelling. The Go is so great on the move and I would like to get also the benefit of playing my PCVR games on it. Is it possible to hook a Go to my laptop and this be recognised by ALVR? Thanks in advance.

**Comment by Colonel-Izzi** [comment]
The only concern there is that the laptop obviously needs to be VR-ready as well, though I'm assuming you've investigated that already.

**Comment by Colonel-Izzi** [comment]
Oh, and obviously you'd need some sort of portable router since there's no way to configure the Go with manual IP address for an old-school device-to-device Ethernet connection.  
  
Maybe there is a way to get your Laptop to assume the role of the DHCP server while directly connected to the Go via Ethernet, but it's been a long time since I've tried to do anything like that so I don't know what the situation is.

**Comment by Kbeam007** [comment]
My laptop is VR ready (GTX 1060 6GB). Thanks anyway, I will look into software options how to turn the laptop into a DHCP server. I think lugging along a router defeats the portability argument...

**Comment by Kbeam007** [comment]
There is a DFCP server app for windows, apparently http://www.dhcpserver.de/cms/
