### ISSUE TITLE
ALVR + NOLO VR

### ISSUE THREAD

**Issue by WJRev** [polygraphene/ALVR#220]
Afternoon,

Has anyone got NOLO VR working with ALVR yet? When I use ALVR the controllers are shown behind and above me. Using the "Apply Offset" I can get myself positioned behind the controllers but not a permanent solution.

I hate VRidge with a passion, I stand in the same room as the ASUS RT-AC3200 that my PC is connected to by ethernet and broadcasting a hidden 5ghz network and still drops out and gives artifacts, and thats at 25mbps bitrate. I can crank ALVR up to 100-150mbps and no problem, looks beaut aswell.

I am not even fussed about wireless functionality.

**Comment by Tux0Topo** [comment]
Hi!!! 
The nolo vr team announced this
https://www.facebook.com/NOLO.Virtual.Reality/posts/714508698929087
Just checked out... and seems to be VERY close to ALVR... like if the nolo team just put ALVR INSIDE their Nolo Home app.... Tomorrow will test further, but so far, seems to be good....

**Comment by WJRev** [comment]
Yeh saw this and first thing I thought was ALVR. Good news and the tracking was perfect when I tried for 10 mins before work.

**Comment by moocow1452** [comment]
I'm having an issue where I can stream in ALVR just fine, but I can't get Nolo VR to work, and I'm not sure why. My guess is that the first time run whiffs because my RX480 is not supported, because I can see and even connect to the Nolo Oculus Client from the ALVR server, but no luck with the Nolo Server.
