### ISSUE TITLE
1.91 working with nolo and driver4vr

### ISSUE THREAD

**Issue by Lightsteed** [polygraphene/ALVR#24]
It works! And its amazing apart from the slightly crappy tracking of the nolo. Dev - not sure of your plans for this project but i would suggest you reach out to nolo and see if they want to integrate it into their software. Currently they are aligned with riftcat which is built to run on any android based hmd, but your software works so much better.

**Comment by polygraphene** [comment]
Thank you for reporting!
Great!

The most attractive point of ALVR is to support Asynchronous Timewarp for smooth head-tracking.
But if we support 6DoF tracking, we lose smooth head-tracking because Asynchronous Timewarp only supports 3DoF tracking.

I don't have a clear plan for future of ALVR.
But, currently, I think that working with NOLO is not a good idea for ALVR.

**Comment by Sp4iK** [comment]
Hi Lightsteed, how did you manage to get Nolo working? I'm trying it with a Samsung S8 and connecting the headset marker directly to the phone (running in dev mode) or through the GearVR usb-otg port won't get recognized. The only way I see it is to connect it to the pc, but in that way if I try to use the controllers it crashes SteamVR and ALVR.

**Comment by Lightsteed** [comment]
I installed virtualhere usb over ip on the phone and shared it through the otg port. But you will need nolo software v 1.9 which is being released tomorrow i think.
