### ISSUE TITLE
streaming will begin shortly

### ISSUE THREAD

**Issue by telapan** [polygraphene/ALVR#253]
I seem to be stuck on 'Connected! Streaming will begin shortly. I have tried different resolutions and bit rates but this does not seem to have any impact. It seems that head tacking is working but no video back to the head set. I have an Oculus Go.

**Comment by TrumX** [comment]
Hi!

So today I set up my oculus go with ALVR. after some work on ports etc it worked after changing codec to 264 since Im using an AMD R290oc.

Im doing it via 5ghz wlan, ethernet to box etc.
strange thing is, I am stuck in that screen too... Interestingly, it worked twice with lowering the resolution to 1024x512 and 1536x768, but to be honest, the quality is underwhelming then.

even on 2880x1440 i have no packet loss, sound gets delivered to my headset and tracking works etc since if I mirror my screen to desktop i can browse through the steam store. headtracking included working.

but still in that fricking "streaming will begin soon" stream.

any ideas?

**Comment by telapan** [comment]
@TrumX  I also have an AMD card. I wonder if that leading to our issue. What port work did you do?

**Comment by TrumX** [comment]
@telapan  Hey mate. I opened in and out for 9944 as instructed. I mean ovbiously it's working with lower resolution, but to be honest, Id rather not play at all than to brun my eyes trying to read stuff ingame on 1500 res (is that 750 per eye?!^^). 
Delay was nonexistent also.

Whats important for me was to set the codec to the 264 and completely deactivate the firewall (in router and on pc) then it worked. Im on Win 7

**Comment by telapan** [comment]
@TrumX Ok, i'll try that. i know i deactivated my firewall. maybe my router is blocking that port.

**Comment by telapan** [comment]
@TrumX Opening the port on my router did the trick. I used the lowest res last night. I will let you know my results with other resolutions.

**Comment by soul666reaver** [comment]
Is it possible its related to the max resolution your monitor can handle? I'm having the same issue. I know the phone can handle that resolution. For example my phone can handle it but my tv (monitor) only has max res of 1080p. This weekend I'll try on the 4k tv in the house. Or super sampling higher res to my 1080p monitor and post results.

**Comment by TrumX** [comment]
I fixed the problem with using a nvidea card and windows 10.
