### ISSUE TITLE
USB Joystick not seen within Injected PC app in Revive while streaming with ALVR (using Gear VR and Samsung S9)

### ISSUE THREAD

**Issue by dpluigi** [polygraphene/ALVR#257]
Hi,

Thank you for putting together such a stable and efficient tool.  I am enthusiastic about VR and AR and exploring the potential of my Gear VR mobile headset while waiting for Oculus Quest to be releas3ed.  Hopefully, ALVR will be able to interface with Quest and make it a wireless Rift little brother so that the powers of PC and graphics card can be leveraged too.

**Back to joystick issue:**
With ALVR (version 2.3.1) I managed to get the graphics streaming to my Gear VR mobile headset fitted with a Samsung S9 over wifi.  The Revive (version 1.6.2.0)  inject function works well and Soaring flight simulator Condor 2.exe (version 2.0.5)  starts apparently normally ( http://www.condorsoaring.com/ ).

My issue is that after starting Condor with Revive, the USB joysticks do not show up in Condor/Input menu, hence to operational while in flight sim).
Note that the joystick USB devices are detected by Windows and can be calibrated by Joy.cpl and listed in Steam/Controller.

Do you have any idea what needs to be done so that once Condor is started in VR mode I get the joystick (and second joystick for my rudder pedals)  recognized and operational?
Is the issue at the ALVR level or Revive level?

Thank you in advance for your help,
Donat

**Comment by pupphelper** [comment]
This doesn't seem to be related to ALVR.  You should ensure your joystils are detected and usable by steam, and perhaps try a different VR game that uses your USB controller to verify the problem.  If the USB Joystick is connected directly to your PC and SteamVR, the problem is likely somewhere in that chain.  If you suspect Revive injector as the problem, try a non Revive injected game see if it works.  If that works, try a different revive injected game to see if it works.   I know that using a PSmove controller setup with PSmove Navigation controllers as standard USB game controllers (via scptoolkit), there are no issues running via ALVR for games like space pirate captain and something like a revive injected roborecall.

**Comment by dpluigi** [comment]
Thank you for your reply.   I checked again and yes the USB Force Feedback Controller is seen in Steam but not VR Steam.

Interestingly the joystick was allowed to move the cursor within the Steam / Big Screen / Setting: Controller...
I tried to modify the default controller in the Big Picture setting and no change.

Today, I noticed that I could start this game from Steam, then the game Input setting I noted that I could define the joystick's input (i.e. the original ones not showing).
From there on,  I was able to close the game, and the launch (Inject) from Revive as before and now the Game/Inputs setting detected and allowed to set it up.
 It working and I am not sure what really changed. 

I realize this is not related to ALVR, but is there a good resource to help me understand how the Steam (In Big Picture) controller are set?  In particular, so that the joystick is not used instead of or in conjunction with the keyboard and mouse cursor.

Thank you again for your help.
