### ISSUE TITLE
Just a HUGE THANKS to polygraphene

### ISSUE THREAD

**Issue by TrumX** [polygraphene/ALVR#276]
No Issue, but just wanted to say that ALVR works just perfect for me.

Im playing on a 1080ti and 5ghz network now and everything runs smooth and looks good (on oculus go with 2880!)

Yes, its not like a normal VR set, but hey, I got to use my Oculus go which usually only lets you play garbage games and I can play Subnautica (having a blast), elite dangerous (just awesome) and dirt ralley with it.

As said Poly, big thanks for this great piece of software which enables me to play VR games for 200€ instead of 800 for a headset.

keep up the good work man!

**Comment by Lyks-tech** [comment]
Hey, what controller do you use with Subnautica ? Because Go only has one 3DoF controller, isn't it very limiting for this game ?

Also, why 2880 as the Go is limited to 1x2556px ? I think it's different from videos quality where, being 180 or 360° it needs huge resolution, but in ALVR it's just the resolution of the cropped frame sent.
Make sure you don't get bottlenecked with the SteamVR Video parameters, which mine was set to 1156px (for one eye I believe so 2312px).

Great project, I wonder if the team, or the guy, will have the time and motivation to make it real for 6DoF full tracking Oculus Quest <3 although it might be difficult to achieve with asynchronous timewarp used by ALVR.

But it would be the fckin way to go, just imagine...

**Comment by TrumX** [comment]
Using gamepad for subnautica, is basically recommended for all vr headsets, because you have a lot of menu usage and hotkeys.

Dunno, looked the best for me, but I will check it out and check my steam vr settings, thanks for the info!

**Comment by kirilldev** [comment]
That thing is so smooth on 5GHz network. The best thing which I found for my GearVR. Thank you.
