### ISSUE TITLE
Skyrim VR not showing up on headset

### ISSUE THREAD

**Issue by tochgl** [polygraphene/ALVR#289]
I tried to get ALVR to work with my oculus go and skyrim vr, but it doesn't show up on the headset, only on my computer. This doesn't happen with any other games besides doom vfr, it works fine with games like beat saber and others that I don't even have the controllers for.

**Comment by Separisa** [comment]
Have absolutely same problem for two days now (first time trying stream skyrim vr). Though works with other games.

**Comment by polygraphene** [comment]
Have you tried Room setup? It's may be caused by height of your head. Put 150cm(or whatever you like) in height from floor.
And enable "Display VR View" on SteamVR and make sure game scene is correctly rendered.

**Comment by Separisa** [comment]
I've made these steps, steamVR room is shown, but as soon as i start skyrimVR the picture in helmet changes from steamVR room to dark gray space of alvr (same as white when connection asked for, but dark gray and with window with loading animation) and nothing happens. I hear sounds of started game, see the game on computer but headset doesnt show it.

**Comment by polygraphene** [comment]
Can you provide screenshot?

Try "Apply offset" on Other tab. Put the values like -1.5 or 1.5 on second text box (which mean height offset) and press Save.

**Comment by Separisa** [comment]
Thank you, polygraphene, for your patience and help.

I solved problem by changing nvidia settings for Skyrim VR game in Nvidia Inspector - skyrim needs nvidia control panel action to force usage of right GPU (the problem is common for skyrim, but absent in other games). But in some new windows 10 versions there is no such control panel available at all. So whoever also has this problem and can not fix it by assigning Nvidia gpu through control panel (common solution in internet) because there is no control panel in OS or game just wont start from it - check the Nexusmods site in section for Skyrim Special Edition for "Possible Dark Face Fix - Player (NVidia only)" solution which also fixes SkyrimVR broken video connection between computer and Oculus Go headset through ALVR.
