### ISSUE TITLE
How can I change the lens distortion parameters?

### ISSUE THREAD

**Issue by off99555** [polygraphene/ALVR#293]
Hi @polygraphene 
I ran the Daydream fork from this guy: https://github.com/sigmaxipi/ALVRClient/
And I noticed that when I put the phone inside the headset case, I noticed a severe double of image. So if I look at a point, I would see 2 points slightly nearby.
All daydream apps work fine except ALVR client.

1. Is the lens distortion parameters set inside the client or server? Which line of code corresponds to it?
2. How do I figure out the proper distortion parameters?
3. When dealing with lens distortion parameters, what are the common parameters that we need to adjust?

**Comment by polygraphene** [comment]
I haven't cared about lens distortion until now. So I'm sorry if I missed the point.

1. Only I know about distortion is that OpenVR accepts some parameters.
https://github.com/polygraphene/ALVR/blob/master/alvr_server/alvr_server.cpp#L281
I haven't seen anything like this on client side (GearVR or Google VR SDK).

2, 3. I don't know. On GearVR, game developers don't need to care about it (I think). Developers only need to render image to specified texture with specified projection matrix.

I noticed the same bad rendering result on DaydreamView for the fork.
In addition, the issue is disappeared on Lenovo Mirage Solo.

**Comment by off99555** [comment]
I don't know if it's about lens distortion or not. I'm just guessing. But I think you know what I mean. I put on the headset and I see a weird double vision that makes me sick. The world looks bigger than it actually is. Try Riftcat/VRidge on DaydreamView and you will see that it works normally.

So to conclude, you did not do any explicit lens distortion. You kind of pass a rectangle image and you expect them to distort for you. 

If you said you didn't see anything like that on the client.
1. I am curious how can the distortion from Daydream be different than Cardboard then? The distortion should be applied somehow at the client side also, right?
2. Or maybe the projection matrix you mentioned is actually what Daydream and Cardboard give you?
3. Do you have any idea where the problem lies?
4. Did you have contact with the guy who did the fork about this issue?
5. If Lenovo Mirage Solo works normally and it's just lens that's different from DaydreamView, it means that there is some misconfigured parameters somewhere?
6. If I buy Lenovo Mirage Solo, it should work similarly to Riftcat, correct?

Sorry for lots of questions. 😄

**Comment by polygraphene** [comment]
The distortion issue still is not resolved, but I pushed new commits support Daydream for both client and server.
Please check master branch of server and daydream2 branch of client.
ALVR.exe has new UI to select resolution for DaydreamView. Select proper resolution or add new resolution for your headset on https://github.com/polygraphene/ALVR/commit/888e315b9a61a1a0a78559ab3dd8bfa013ba4f19#diff-dcf0c227aab1648887255dbeb09b5b45R56

**Comment by polygraphene** [comment]
The commits partially fix double vision problem. But still have weird stretching of vision when I rotate my head. This issue is only on DaydreamView. Mirage Solo has no issue.

I suspect the issue is in FOV instead of lens distortion. FOV settings in degree which is provided by GVR sdk are here.
DaydreamView(2017) left eye: (left,right,top,bottom)=(53.000004,45.000004,53.0,44.0)
Mirage Solor left eye: (l,r,t,b)=(45.99999,44.999996,45.999992,45.999992)

DDView has asymmetric FOV, left is 53 degree and right is 45. I think it is the cause of stretching issue.
While Mirage Solo have (almost) symmetric FOV which are all 44-46 degree.
I suspect that server and client use different method to process FOV (and projection matrix) and produce different distortion.

Server provides correct FOV parameters into SteamVR now.
https://github.com/polygraphene/ALVR/blob/master/alvr_server/alvr_server.cpp#L281

The projection matrix is generated by FOV parameters.
http://www.songho.ca/opengl/gl_projectionmatrix.html
https://github.com/ValveSoftware/openvr/wiki/IVRSystem::GetProjectionRaw

1. No. Daydream and Cardboard has the same rendering flow. I think the different is FOV.
2. Yes. The projection matrix provide some kind of distortion.
3. I think that is FOV.
4. Yes. I have not contacted him for months. I will try to contact him.
5. I was thinking yes. But the issue is still there...
6. Yes.

**Comment by off99555** [comment]
It could be the lens issue or the screen issue. Because those 2 are the only sources of difference between Mirage Solo and DaydreamView.

---

I have no experience with Android development. I wanted to build the apk so I opened this in Android Studio and it keeps loading. What should I do?
![image](https://user-images.githubusercontent.com/15215732/57579830-e9ba6200-74cb-11e9-9e5d-e03685f31f1d.png)
Meanwhile, maybe you can upload me an apk here?

**Comment by off99555** [comment]
Updated: It looks like this now: 
![image](https://user-images.githubusercontent.com/15215732/57580399-48cfa500-74d3-11e9-8630-4d1e2b05a85f.png)

**Comment by polygraphene** [comment]
Could you build apk?

[app-Github-Normal-Daydream-debug.zip](https://github.com/polygraphene/ALVR/files/3169936/app-Github-Normal-Daydream-debug.zip)

I changed following line to "true" for more detailed logging.
https://github.com/polygraphene/ALVRClient/blob/daydream2/app/src/main/java/com/polygraphene/alvr/Utils.java#L9

Please make sure to use latest server of master branch.

**Comment by off99555** [comment]
I could not build apk because of the error mentioned in the picture above.
I checked your apk with the latest server commit and I saw stretching issue as you said. The double vision seems to be eliminated. There seems to be more packet loss and jittering than Daydream fork there. But good progress!

**Comment by polygraphene** [comment]
@off99555 
1. It's not because of resolution. I pushed new commits to fix packet loss issue. Please check it.
[app-Github-Normal-Daydream-debug.zip](https://github.com/polygraphene/ALVR/files/3190335/app-Github-Normal-Daydream-debug.zip)

2. Lens issue is still there. I have not yet got any clue to solve it. It needs more experiment to determine the problem.

3. Yes. That's correct.

**Comment by off99555** [comment]
@polygraphene Thanks. I'm checking the new file. For the DaydreamView lens issue, it's fine for now as long as it has no issues for Mirage Solo.
