### ISSUE TITLE
garbled and distorted sound on Quest

### ISSUE THREAD

**Issue by jadflat** [polygraphene/ALVR#319]
having problems with the sounds, it's heavily distorted and garbled.

connecting via 5ghz to PC on lan cable with Oculus Quest.  have tried it standing right next to the router, still the same issue.

**Comment by ejwilburn** [comment]
I had the same issue and I found that switching my sound card to output to the rear speaker ports instead of the headset fixed the issue, you just have to remember to change that before launching ALVR.

Another work-around someone else posted was to plug in a USB headphone adapter or sound card and use that as the sound source in ALVR and that fixed the issue for them.

**Comment by jadflat** [comment]
Thank you, I'll give it a go

**Comment by jadflat** [comment]
For some reason the Steam Streaming sound device set itself up as 7.1 channels, changing it to stereo fixed the issue

**Comment by GandalfTheGreen101** [comment]
Where do you find steam streaming sound device so I can change it to stereo?

**Comment by jadflat** [comment]
Under playback devices in the sound settings

**Comment by GandalfTheGreen101** [comment]
Which sound settings? Steam sound or pc sound settings?

**Comment by jadflat** [comment]
windows sound devices
