### ISSUE TITLE
How to get SubmitLayer DepthHandles

### ISSUE THREAD

**Issue by rishi-rranjan** [polygraphene/ALVR#342]
This is no a bug but we are working on depth capture to alleviate large network latency. When we log the delthHandles in SubmitLayer , it's NULL. Is this something we need to do in ALVR driver or I should ask this on OpenVR forum? 

`[10:36:49.192 748] SubmitLayer Handles=00000000C0001202,0000000080002D82 DepthHandles=0000000000000000,0000000000000000 0.000000-1.000000,0.000000-1.000000 0.000000-1.000000,0.000000-1.000000`

**Comment by polygraphene** [comment]
Unfortunately, it is said that depth texture is passed only for Oculus driver.
https://github.com/ValveSoftware/openvr/issues/825

I also want to know about depth texture. If you get any clue to get depth texture, please let me know.

**Comment by TheWhiteAmbit** [comment]
Since Oculus also broke their depth layers in April 2019 release, I will be using my own Quad-Overlay system with depth compositing for Oculus Rift and HTC Vive in the future. Haven't tested if Oculus fixed their depth layers in a later release. But since Oculus and Valve are so unreliable on their releases, it is probably the best way to not use anything but the bare minimum needed from their SDKs. Specially since they tend to not only break things in their respective SDKs (these Errors can be found before release), but also in their Runtimes that can be updated anytime. 

We had several experinces of customers writing eMails about our "stupid software not working" when everything was perfect at release. It was due to broken Runtime Envirionments with forced live update on client PCs. We then had to find a workaround and have a complete software roll-out. Now we go with the workarounds/own implementations wherever we can. It is really sad to see so little effort on software quality with both major VR-Headset manufacturers
