### ISSUE TITLE
ALVR with Sansar through SteamVR on Oculus Quest- does not see  tracked controllers. 

### ISSUE THREAD

**Issue by Wollerby** [polygraphene/ALVR#393]
ALVR and My Oculus Quest works nicely on many games through Steam. There are some controller recognition issues. Specifically, Sansar launches through SteamVR (using the above setups) but only plays on the desktop. It does not see the tracked controllers Do you know of any workarounds and is this something that ALVR may eventually address?

**Comment by polygraphene** [comment]
I tried it and also have same issue.
This game may have its own detection mechanism on VR HMD. I couldn't figure out the exact mechanism, but it may be difficult to solve it from ALVR side.

I found a similar post.
https://steamcommunity.com/app/586110/discussions/0/1840188800793903121/

**Comment by Wollerby** [comment]
Thanks. Checked with Linden and their response:
_"At the moment, Sansar only supports the HTC Vive and Oculus Rift. We do not support the Oculus Quest.Using ALVR should, as far as I understand, bypass the issue that the Quest itself uses a different OS and not Windows. But without a way to recreate your issue, we are largely unable to troubleshoot it."_
My guess that if Linden remains serious as a VR platform, and with the growing popularity of the Quest (with its un-tethered 6dof  qualities) solutions will emerge. 
I'll be making a dono to ALVR this weekend. 
Thanks again.

**Comment by xxValiumxx** [comment]
Hey guys.  I'm the one responsible for getting the Windows Mixed Reality headsets working in Sansar again.  It's an implementation issue on their end, but thankfully easily fixed.  I'll dig into this and try and get it fixed for us.

@Wollerby I know what the issue is.  
@polygraphene It's **not** an ALVR issue.

**Comment by Wollerby** [comment]
@xxValiumxx - very good to know. I will monitor any developments.

**Comment by xxValiumxx** [comment]
@Wollerby okay, so without having done any actual work in the fixing, I've noticed a similarity in both the current state of Windows Mixed Reality, and ALVR, as behaving in Sansar; for the hands to begin to track in avatar control mode (as opposed to the menu mode, which works fine, incidentally) you have to teleport forward just the once.  Because of the current state of mapping, you need to press the right stick precisely forward and then click it to teleport, your hands will then track more or less correctly (I have an issue where it appears my camera is too far back and a bit higher than it ought to be.)

**Comment by Wollerby** [comment]
Hi. Thanks for the update. I'm sure you're correct but, for me, no luck. I downloaded the program from Sansar directly (on the desktop) - loaded up ALVR on Headset and Comp but it does not even go into VR mode so I can try your suggestion. 

Also tried F9 to toggle, no dice.

I suspect I am doing something lame on this end. The VR just shows a launch screen with some squiggly movements indicating it is doing something - but no luck.  There may be a confusion in the fact that I have it both installed in Steam and also independently on the PC. 

The PC version runs a perfect 2d version (like Second Life) but I've not found a way to get this into the VR domain.

Congrats on the Quest and looking forward to seeing what you discover.
