### ISSUE TITLE
Virustotal reports Viruses with both .exe and .zip (alpha 5)

### ISSUE THREAD

**Issue by jackfruh** [polygraphene/ALVR#399]
Hi, Virustotal.com is reporting both the .exe and the .zip version have viruses.

Could you upload them there and look at the output and see if there's any merit to what they are saying?

Thanks!

**Comment by POEDaley** [comment]
That's a false positive.  These are beta/alpha drivers that don't have proper signature.  When uploading you'll see that very few scanners actually report something.  Normally with 0 day alpha stuff in general you'll see this.  It's quite normal.

**Comment by zxsdklfhskyrvk** [comment]
Rescanned the zip, and no issue reported - https://www.virustotal.com/gui/file/9f579ddbaa74cd7010b95552f1d3f1180e062b179c0145b9bfc4fb1d45089ce4/detection

**Comment by jackfruh** [comment]
Awesome - can't wait to try this - are there instructions anywhere on how to install from the zip file?
(I understand unzipping, but don't know where to put these and how to get them registered in the needed places for SteamVR to pick them up.)

**Comment by polygraphene** [comment]
Anti-virus complains that many times.
#141 #190
exe is still detected as an adware.

@jackfruh Extract anywhere you want. ALVR installs driver automatically when starting StreamVR. You can also manually install by "About" tab.
Please make sure extract directory name doesn't contains non-ascii character.

**Comment by jackfruh** [comment]
I got it working - this thing is incredible.
What can I do to help its development?
When I unzipped the files, there were a few batch files I ran to configure steam to use the driver - is there somewhere I can submit a guide to share with others?

I tried the game Moss on steam, and I once I got the menu up, I couldn't 'click' anything.
Is there a guide for mapping controls?

Also the graphics quality was fantastic as it was coming from my PC, but image was a bit jumpy, as if the location information was delayed making the round trip to the PC - I'm going to go buy a new 5ghz wireless access point to see if that helps, any other tips/guides for performance?

- Jack

**Comment by zxsdklfhskyrvk** [comment]
5Ghz is better, and you need to be in the same room as the router.  If you already have one but aren't in the same room,  give that a try before spending more money.  

But it seems there could still be some framerate related issues, possibly stemming from the Nvidia (?) driver involved.  So that wouldn't be something ALVR could fix.  A TBD at the moment.  Just guessing here.

**Comment by POEDaley** [comment]
I use a 5ghz ap connected directly to my PC via a USB NIC.  Only thing that is connected to it is my Quest.  If you get one, just make SURE it has a GBE port on it.  Many 5ghz APs have just 10/100 since they use a weaker processor in it.  The GBE ones will be much stronger and reduce transport latency as much as possible.
