### ISSUE TITLE
Steam says an error occurred  while updating steam vr (app running)

### ISSUE THREAD

**Issue by mynameisnotalec** [polygraphene/ALVR#440]
When i press trigger on the quest this pops up 
Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=1 NvEncoder::LoadNvEncApi : NVENC library file is not found. Please ensure NV driver is installed at c:\src\alvr\alvr_server\nvencoder.cpp:70

and steams say error occurred while updating steam VR (app running) 
Any idea why?

**Comment by mynameisnotalec** [comment]
When i press trigger on the quest this pops up 
Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=1 NvEncoder::LoadNvEncApi : NVENC library file is not found. Please ensure NV driver is installed at c:\src\alvr\alvr_server\nvencoder.cpp:70

and steams say error occurred while updating steam VR (app running) 
Any idea why?

**Comment by POEDaley** [comment]
Open task manager and make sure that VRserver.exe didn't get stuck.  I know this happens from time to time.  If open, just kill it and try again.  May or may not be it, but it sounds related.

**Comment by mynameisnotalec** [comment]
Still the same problem

**Comment by DocLock17** [comment]
I was just about to write a new thread but your issue seems related to a Luddite like myself and so I think it stands a better chance of figuring out both problems if I post here.

Upon launch the client allows me to "start server" at which point steam begins to launch. The following error code pops:

Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc CreateEncoder failed. Code=15 NvEncoder::CreateEncoder : m_nvenc.nvEncInitializeEncoder

And my computer screen goes dark.

Now, as expected the darkness is the SteamVR app opening an empty port on my desktop and if I WINDOWS out of it, I now can acknowledge the error and even "connect" to the Oculus Go I am working with.

Now let's say we go ahead and close the SteamVR screen and "connect" to the headset
At this point, a message lets me know that 
"Unexpected SteamVR Error"  happened and SteamVR has encountered a critical error
If I wait until after this crash and attempt to re-launch SteamVr I get the following ALVR Crash Report

Unhandled Exception.
ExceptionCode=C0000005
Address=00007FFF0F4AA036 (00007FFF0F490000 + 000000000001A036)


My only fear is that the fact that I use Trinus with the PSVR might be a problem, but this issue seems like it is all where over my head! Needless to say, any help fixing this whole problem would be great! LOL
