### ISSUE TITLE
Was working, today SteamVR will start up, then fade to black

### ISSUE THREAD

**Issue by ErickOnassis** [polygraphene/ALVR#472]
I have been trying to get SteamVR streaming to my Quest for the past 2 days with no luck. It's been working flawlessly up until now. Whenever SteamVR starts up, it fades to black, that's it. I can see the Guardian still but nothing but blackness. I've uninstalled & re-installed ALVR, I've tried an older version all with the same results. As I said I have been using it for about a week with no problems so any tips or help here would be greatly appreciated.

**Comment by pdebaty** [comment]
I'm having a similar issue (although I never got it to work since I started trying about 2 days ago). My ALVR server discovers my headset and I'm able to connect, then start SteamVR, but then all I see (in the Quest) is either a black screen with the 3 loading dots forever, or a red screen with some unreadable artifacts.
