### ISSUE TITLE
two controllers in ALVR

### ISSUE THREAD

**Issue by chapeka** [polygraphene/ALVR#50]
HELLO again.
Do you think is possible to use two controllers 3dof in your app¿?? I say two gear VR controllers or two Oculus GO controllers with ALVR, connected via your app instead via oculus drivers and software...

**Comment by polygraphene** [comment]
https://github.com/polygraphene/ALVR/issues/47#issuecomment-396910043

**Comment by Kroktar** [comment]
https://forums.oculusvr.com/developer/discussion/52214/would-i-connect-two-gearvr-controllers

**Comment by chapeka** [comment]
something new here?¿?¿? if we have possitional tracking in the headset this solution may be very possitve for the proyect, and remmaping the bittons or combining them it will be cool

**Comment by AltoRetrato** [comment]
With the Oculus Go I can use its own controller plus a Gear VR controller, thanks to https://github.com/polygraphene/FreePIEVRController - but I'm currently using only the buttons on the Gear VR controller. I still have to write a script to translate the controller position from the right to the left hand in order to use it as the left hand controller in SteamVR.
