### ISSUE TITLE
Tracking issue.

### ISSUE THREAD

**Issue by AzadNezamdoust** [polygraphene/ALVR#520]
My head and controller moving even when I am still.
Tracking is super smooth outside LAVR app but when streaming it is moving randomly.
Also, I have only one controller.

**Comment by McDonldHamburger** [comment]
Same with me.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pvtpaula** [comment]
For all i know the version you can download here is not compatilble with the newest Quest Firmware. For an easy fix try Downloading and installing 'Sideload'. A wonderfull app for user generatet content. There you have easy acess to a ALVR version that has the fix for the 'oinly one Controller' Problem.

**Comment by AzadNezamdoust** [comment]
Thanks. Still my tracking issues are not resolved. Also in every few
seconds it gets a stutter. Connection and speed is fine.

**Comment by DavisNT** [comment]
For Oculus Quest you can try [JackD83's fork](https://github.com/JackD83/ALVR). 
It works only with Quest, and it has several Quest specific improvements.
