### ISSUE TITLE
Now that ALVR client is on the app store can we have more automations?

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#57]
I don't want to touch my PC so I'd like to always run ALVC server on the tray and whenever my "auto-connect" client starts up the server should "Start Server". Also after disconnection from clients and after X secs of inactivity I'd like it to stop the server and maybe kill the steam vr services so my CPU doesn't burn to the ground.

Maybe add wake on lan as well so that whenever the client starts it wakes up the last server it connected to.

This way I'll never have to go to my PC room ever again.

You could also allow me to automate this manually. What I'd like is on the server side: "Run this app on connect" , "Run this app on disconnect".
On client side I'm not sure I can do the wake on lan thing externally. I think whatever oculus app is on foreground everything else like tasker stops working. It would be cool though if I could run a tasker task on startup.

**Comment by polygraphene** [comment]
It's an interesting idea. It would be nice if users can ignore all bothersome operations.

>"Run this app on connect" , "Run this app on disconnect".

It's a good idea. It can be used for general purpose and very useful. I will add this feature on next release.

>On client side I'm not sure I can do the wake on lan thing externally.

I think I can add WoL on client side, but this lacks versatility. As you said, Using Tasker may be good.
But can Oculus Go run Tasker?

**Comment by polygraphene** [comment]
Okay. I will try to integrate with Tasker.

This document may help us.
https://tasker.joaoapps.com/developers.html

Server side has been done on the new release, v2.0.4.

**Comment by Lightsteed** [comment]
What is the usecase for the run app on connect or disconnect?

**Comment by vrokolos** [comment]
To start steam vr or stop steam vr and launcher, raise volume to full, change soundcard to bluetooth, disable notications and/or automatically starting last game played without touching the pc

**Comment by Lightsteed** [comment]
Yah ok fair bump

**Comment by Jbbrack03** [comment]
I think that the biggest challenge to the usefulness of this idea is the fact that the controller and speakers/headphones still need to be connected to the PC. You might be able to go one room over if this is implemented, but that's about it. And we'd have to figure out a way to get SteamVR to open in Big Picture Mode as soon as ALVR connects, otherwise you wouldn't have a way of launching games if you're not in front of the computer. 

So overall I agree with adding some automation, but the ability to have your controller paired to your headset needs to be revisited. I've been using Moonlight lately to stream 2D Games to my Oculus Go, and it works extremely well with the controller paired to the headset. Other users have used VirtualHere with ALVR to be able to pair the controller to the headset. I know that there have been concerns about it affecting latency, but it doesn't appear to be with 3rd party implementation. And you'd think that having another App running at the same time would add even more potential latency. So a native implementation seems to be viable.

**Comment by vrokolos** [comment]
I have replaced steam vr home with bigpicture beta so I can launch games remotely without touching the pc.

**Comment by vrokolos** [comment]
you have to change a vrmanifest file in steam folder to do that

**Comment by vrokolos** [comment]
I agree thought. If somehow instead of reimplementing moonlight you could integrate it it would be awesome

**Comment by Lightsteed** [comment]
I managed to get my steam controller working using steam link running on the go today. So can control big picture with it. But i realised it was better and easier to do that through my phone so i didnt have extra shit running on the GO. It worked for playing 2d games thru virtualhere, but I dont have any vr games that use gamepad controller so wasnt able to test if it worked for native vr games too. But i agree, an inbuilt solution is best.

**Comment by vrokolos** [comment]
Now that run command on connect/disconnect can you make it so server starts by default and listen for client connections without steam VR open and only run steam VR whenever a client connects?

**Comment by polygraphene** [comment]
>listen for client connections without steam VR open

All communication with client is done in Steam VR driver. So we cannot implement it by design.
It is possible to create external tool to listen client broadcast and start ALVR.

For example:
https://gist.github.com/polygraphene/d4b5ebe6946a8526ce7015098c991a7d

**Comment by vrokolos** [comment]
nice!! thanks!

**Comment by vrokolos** [comment]
Ok I modified your code to this for my raspberry pi that is always online so that it automatically wakes up the PC and starts all the VR services / changes resolution / priorities etc:

https://gist.github.com/vrokolos/8a884f9d83dbb80a69be6ffc2245f27d

**Comment by vrokolos** [comment]
This works fine. Here is what I'm doing on VRON on my PC with Everghost for anyone looking to automate

![image](https://user-images.githubusercontent.com/278046/41642771-ec5d6184-7471-11e8-80ee-9ccb94e62cc4.png)
