### ISSUE TITLE
high latency

### ISSUE THREAD

**Issue by avoidplox** [polygraphene/ALVR#573]
Hey,

I just bought a Oculus Quest and tried with using ALVR. Unfortunately I have very high latency.
On Riftcat it was working fine. No matter what, it keeps up the latency high. I am using a 2.4G wifi connection on the pc, and a 5G on the Quest.
PC Specs
1080 Ti
32 GB Ram
i7-8700K
Not sure what could fix this problem.

![Screenshot_1](https://user-images.githubusercontent.com/58009211/71760668-62d65180-2ec1-11ea-811e-92ab5de56c81.png)

**Comment by LegacyGamerHD** [comment]
5g on the pc is also needed

**Comment by LegacyGamerHD** [comment]
or ethernet

**Comment by RAJ-Huff** [comment]
Ordinarily you'd use ethernet to wire your PC to the router, 2.4GHz on a computer (especially of those specs) is barbaric.  Then use 5.4GHz with only limited channel selection to the device.  
Alternatively, you can use a USB WiFi adapter and use network sharing so that the device can connect directly to the computer.  Again, 802.11 AC (5.4 GHz) is preferable.  ALVR is superior to riftcat, but requires better networking hardware to facilitate it.
