### ISSUE TITLE
I can make a Chinese translation for the ALVR

### ISSUE THREAD

**Issue by bbbird5** [polygraphene/ALVR#675]
I like this software, I can make free Chinese translation for the software and introduction page
Please tell me what to do

**Comment by vleeuwenmenno** [comment]
I am not involved in this project but I thought I'd message back anyway because I can clearly answer this.

Basically from looking at the code quickly I can see that most of not all the labels and texts are hardcoded into the C# files.
If you wish to translate you'd have to wait for them to make/implement a centralized language system. Or make a completely different branch and change all the labels in code. (And maintain the rest of the logic to stay up-to-date)

To say it simply: At the moment you can't translate this software easily.
