### ISSUE TITLE
distorted screen on quest 2. is there any paln to support quest 2?

### ISSUE THREAD

**Issue by david419kr** [polygraphene/ALVR#683]
same as title. I've just recieved my quest 2 today, and ALVR connects fine, but screen is distorted.

is there any plan to support Oculus Quest 2?

**Comment by mathyou9** [comment]
I also have this as a bug. Is there any updates on this?

**Comment by jshow14** [comment]
Same issue here. Quest 2 with most games gives at least some kind of weird distortion effects. Blade and Sorcery looks like it's set to negative IPD lmao

**Comment by Espionage724** [comment]
Are you all using IPD 3? I'm using ALVR [from this repo](https://github.com/JackD83/ALVR), and [with this issue report](https://github.com/JackD83/ALVR/issues/318), it seem IPD 3 is broken in ALVR.

**Comment by jshow14** [comment]
> Are you all using IPD 3? I'm using ALVR [from this repo](https://github.com/JackD83/ALVR), and [with this issue report](https://github.com/JackD83/ALVR/issues/318), it seem IPD 3 is broken in ALVR.

Nope, I use the 1 setting for IPD. I’m a cyclops. 😂

**Comment by oOKonanOo** [comment]
**Visual distortion when using ALVR with Steam VR and Quest 2**

Same Issue for me, to add a little more detail.  I'm Oculus Quest 2 on ALVR 12.4.1 downloaded from https://github.com/JackD83/ALVR/releases.  I'm running a Radeon RX 5700 XT with Ryzen 7 2700X and Radeon Software 20.4.2.

The problem seems to be with the interface between Steam VR and ALVR and it's understanding of headset orientation.  When ALVR server first connects to the client on the Quest 2 (white background, black grid, ALVR text) all is fine, I can look around and change headset orientation and everything is perfect.  Once Steam VR home loads however, the visual distortion starts.   There are various things wrong with the view, including incorrect "depth" but the most obvious noticeable distortion is when you tip your head to the side.  If you tip your head to the right (clock wise viewed from the rear) , the geometry skews so as to render vertical lines still vertical when they should now be rotated to the left (anti clockwise).  What was a square is now a rhombus! I've tried adjusting a variety of settings and haven't been able to cure this.    There are clearly people using Quest 2 and ALVR as I've read plenty of reviews, there are also clearly at least a few others with this issue though.  Any help would be greatly appreciated.  I love my Quest 2, but desperately want to use it now to access my Steam VR library.

**Comment by oOKonanOo** [comment]
> Are you all using IPD 3? I'm using ALVR [from this repo](https://github.com/JackD83/ALVR), and [with this issue report](https://github.com/JackD83/ALVR/issues/318), it seem IPD 3 is broken in ALVR.

This was the issue for me.  The problem occurs when I've moved the eye-pieced in the headset as far apart as they can go.  If I move them to the central position, everything works perfectly :-)  I think I must be IPD 2.5 as I'm quite comfortable in either of those lens positions.  Thank you for the fix! :-)

**Comment by nuevakenia** [comment]
i got the same problem, when i look arround its looks like warped distortion, i use ipd 3 with quest 2.
its there any setting that can help with this? or we have to waiting to an update?

**Comment by oOKonanOo** [comment]
The other thread about this issue has a post from the developer saying it
will be patched 'next week'.  For now, if you can still see ok, move the
lenses to central IPD 2 position. ALVR then works fine.
