### ISSUE TITLE
The app won't install on the Oculus Go

### ISSUE THREAD

**Issue by Ludendorff** [polygraphene/ALVR#695]
I redeemed the code and the app appears in the not installed category but when I click on it to install it fails at 72kb and won't install.

**Comment by seanj200** [comment]
I've got the exact same problem. Any solution?

**Comment by YikesRequired** [comment]
me aswell

**Comment by CevapciF** [comment]
me to :-1:

**Comment by 3ocsi** [comment]
Hi, same issue... Any solution? Thanks

**Comment by Ekristoffe** [comment]
hello how do you install the app guys ?

**Comment by distance0331** [comment]
Same issue! hopefully there is a fix avail soon

**Comment by Not-AriStienfeld** [comment]
where could we get the oculus go app source code so that people with ADB can sideload it?

**Comment by distance0331** [comment]
still no fix for this issue? was really looking foward to this working.

**Comment by mavrick32** [comment]
same

**Comment by Ekristoffe** [comment]
ok it seem the Oculus GO App store doesn't have the file anymore but the link is still valid ...
Please try with this :

Install from apk
- Need to enable developer option for Quest.
- Download apk from [Releases](https://github.com/polygraphene/ALVR/releases)
- Check [Installation](https://github.com/polygraphene/ALVR/wiki/Installation).

**Comment by polygraphene** [comment]
Currently there's something wrong on store page of ALVR.
I'm trying to fix it, but it may take long or cannot be fixed because app submission of Go is no longer supported on Oculus Store.

I'm currently trying to make contact with Oculus Support.

Please try apk for now.

**Comment by dagelf** [comment]
Similar issue on Oculus Gear VR. I last got it working end of Dec, but had to clear cache and data, and reinstall after every run - it would run once and then I would have to uninstall through phone UI, and reinstall inside VR, and then it would work for one more run. Now it doesn't install at all, it just runs up to 2.2MB and then goes back to the "Install" button.

**Comment by polygraphene** [comment]
I have got the following response from Oculus.

> Hello,
> 
> Your Go app was not approved for the Store and therefore is not available for download or installation. Go and GearVR apps are no longer being accepted for the Store and are not being published.
> 
> Because of this, we are not able to help resolve your issue. Please let me know if you have any further questions.
> 
> Best,

So, I discontinue the key distribution. I'm sorry I couldn't be your help.

**Comment by CloudzInnit** [comment]
@polygraphene If possible could there be a verson of ALVR for oculus go that you can side load?

**Comment by polygraphene** [comment]
@CloudzInnit Use https://github.com/alvr-org/ALVR for Go.

**Comment by dagelf** [comment]
Thank you so much for supporting it up to now. I suspect that Samsung and Oculus suits are having some sort of licensing fee showdown. I will not buy any Oculus or Samsung again in future, and discourage same for everyone else if they don't sort it out. 

I managed to install this again with older versions of Galaxy Gear VR system APKs. I want to try create instructions that will work on any Gear VR phone - at the moment it appears that Gear VR can not be installed or activated on a phone that doesn't have it already. Still investigating.

**Comment by Ekristoffe** [comment]
@dagelf it is more Oculus want to force ppl to buy the quest 2 ... what a shame ...

**Comment by bionickaleb** [comment]
telll  me how to  fix ittttt

**Comment by dagelf** [comment]
You can still load the APKs for the games in GearVR if you have them, with adb, including ALVR.
[com.polygraphene.alvr.oculus.zip](https://github.com/polygraphene/ALVR/files/6621920/com.polygraphene.alvr.oculus.zip)

$ adb install com.polygraphene.alvr.oculus.apk

I have tried this on a few phones now. It works great... no issues, not even the one mentioned above - the only problem is that it only works if you have had it previously installed it on your Gear VR library - there is some sort of store link stored in your profile. I am not sure how to link it now that the store link for ALVR is gone. 

<rant>Then, about GearVR - you can still  install GearVR itself - but you can't install anything through the store, everything just gives an error, it's been nerfed by Oculus - whether by accident or on purpose... "by accident" makes good cover... plausible deniability... and I've seen it used as an excuse before. That a dispute between two Billion dollar companies needs to go to such lengths... sad. I don't think the people who are responsible even know what they're doing, or why, at this point... like when people figure out how to make money, and then just make as much money as they can, not even knowing what for.</rant>

I am hesitant to post instructions here because they might break this too.... but then we will just go deeper I guess. Or build an alternative.
