### ISSUE TITLE
Crackled sound with new 2.1.3... and no sound with arcore

### ISSUE THREAD

**Issue by Tux0Topo** [polygraphene/ALVR#70]
The sound is cracking and delayed with the normal version.
And no sound at all with the arcore version. Dont know if this was wanted in this particular version.

Forgot to specify that i´m on GearVR + S7

Thank you for your awesome work!! Hope that paypal help you...

**Comment by Lightsteed** [comment]
sound is working fine for me on normal, using Oculus Go

**Comment by Tux0Topo** [comment]
I´m on GearVR + S7... maybe some problem there? Also, some pal in a Telegram group has no sound in Go with any of the version...

**Comment by Lightsteed** [comment]
Did he check the client is the right version and sound it activated in the server?

**Comment by vrokolos** [comment]
I'm on an exynos s9+ and both ARCore + Normal version work fine with perfect sound

**Comment by Lightsteed** [comment]
whats the tracking like with ARcore? can u make a video?

**Comment by polygraphene** [comment]
Can you get `adb logcat`?
I think it is caused by sound buffer overflow on client side.

**Comment by vrokolos** [comment]
I'm not really wowed by the 6dof. Maybe I didn't test it correctly. I tested it for 5 minutes on Skyrim VR. It was night so I don't know if it works better during day since it uses the camera or I should try it in another room more suitable for ARCore? I don't know.

The tracking works. You can lean, crouch and even walk but sometimes there is lag and some other times it drifts to the side or backwards. As I said I don't know if it was affected by the lowish light or the room I was in.

Anyways I hate walking or crouching while playing. I just want to sit down and play with a gamepad. I haven't tried a vive / rift or other dedicated headset and I really can't understand what the fuss about the 6dof is all about. 3dof is perfect for me with a gamepad while sitting down.

Maybe tell me what to try and change my mind? Currently I prefer the normal version. Maybe if there was an option to disable walking using 6dof and only use it for crouching / leaning I could use more of it.

**Comment by Lightsteed** [comment]
Try out TheBlu on steamvr. Its free and looks lovely, and u can use it with just the go controller. Have a walk around and get uo close to things. 6dof is true vr imo

**Comment by penkamaster** [comment]
@vrokolos I agree that playing 3 dof for headset is enough if you are playing with a gamepad.
6 dof has to be acompanied by 6 dof controllers.

**Comment by vrokolos** [comment]
@Lightsteed I will test it tonight but as I said I hate walking blindly on a room full of objects and I can't be arsed to create spare room for VR gaming. I wanna sit down :)

@penkamaster Yeah I don't have any controllers so that might change my opinion. I'm waiting for steam knuckles to accompany my gear vr + ALVR. But I love playing with a gamepad + VR. It's comfortable and you don't have to move :P
