### ISSUE TITLE
Add Moonlight (Gamestream) support ?

### ISSUE THREAD

**Issue by dusan-t** [polygraphene/ALVR#73]
It would be interesting to see if using Nvidia's Gamestream with Moonlight would increase the stream quality, both visually and latency wise. Riftcat/Vridge devs implemented NVENC streaming by them selves but reports were that it wasn't as good as Moonlight, so they included Moonlight support as an option. 
I'm mentioning this anecdote because what usually comes to mind as a response is the fact that Moonlight also uses NVENC so it should be the same, but in practice Moonlight often wins over 'in-house' NVENC. It even works better than Nvidia's own shield client app.

**Comment by polygraphene** [comment]
I think it is difficult to leverage ATW with Moonlight solution. Because ATW needs the information of which frame is corresponding to which head orientation. If we use Moonlight, it is difficult to get those information by output frame of Moonlight.

I believe that we can achieve the nearly same performance as Moonlight. I have implemented one performance feature (adaptive IDR frame insertion) on v2.1.4. And I will add FEC support which Moonlight also supports. Please refer #42.

**Comment by dusan-t** [comment]
That's good to hear! Thanks for investigating this matter deeply.
