### ISSUE TITLE
I want to support 6DoF tracking? 

### ISSUE THREAD

**Issue by sols000** [polygraphene/ALVR#79]
Many games in steamvr needs 6DoF support.
What if I disable the Asynchronous Timewarp?
Can you give me some suggestions.

**Comment by polygraphene** [comment]
You need ARCore supported device (Galaxy S7,8,9) or NOLO VR with driver4vr to get 6DoF on ALVR.
Asynchronous Timewarp is not related to 6DoF. And if you disable it, you will just get a stuttering head tracking.

Please refer #8.

**Comment by Lightsteed** [comment]
Driver4vr is bringing a new feature soon that will allow you to use vive or oculus tracking to get 6dof with ALVRA. Or you can do it right now with psmove, kinekt or freetrack tracking.

**Comment by VRtinker** [comment]
@polygraphene 
First and foremost, congratulations on your stunning piece of software! It's easily the best mobile VR app there is PERIOD! Somehow echoing what @sols000 was asking here, I was wondering if it would be possible to expand ALVR server to support 6Dof for the headset, in particular, by making it cope with this:

https://github.com/cboulay/PSMoveService/wiki/Virtual-HMDs.

Building a ping-pong-led tracker is a pretty trivial task (if it wasn't for the fact that LEDs, resistors and ping pong balls are usually sold in >1 quantities, it can be achieved with under $5), and PS3 EYE cams are incredibly cheap, at least in the US (you can get them for $1.99 at Gamestop, or ~$5 on Amazon).

Presently the VirtualHMD created and passed to SteamVR by ALVR seems to "reject" the positional coords that [PSMoveSteamVRBridge](https://github.com/HipsterSloth/PSMoveSteamVRBridge)+[PSMoveFreepieBridge](https://bitbucket.org/hawkinse/psmovefreepiebridge) are producing. 

[PSMoveSteamVRBridge](https://github.com/HipsterSloth/PSMoveSteamVRBridge) works perfectly with ALVR when only using it to track PS Move controllers as vive wands (but it's hard to benefit from it because any neck movement breaks the relationship/distance with the hands, if that makes any sense).

What it would seem to be needed, like somebody mentioned in #8, is, like in Riftcat, an option to use "FreeTrack position" in conjunction with GearVR/OculusGO 3DoF IMU.

It would seem that having an option to feed to SteamVR an alternative type of VirtualHMD that supports 6DoF (rotation from IMU + position from FreeTrack) would do the trick!

If you don't have to time to implement this, or it falls outside the scope of the features you plan to have, would you be able to provide a few pointers on where to start looking in the code to attempt said changes?

Keep up the amazing work!
