### ISSUE TITLE
Stuck on saying, "Connected! Streaming will begin soon."

### ISSUE THREAD

**Issue by jiink** [polygraphene/ALVR#93]
Using GearVR with S8, connected to Windows 10 PC with GTX 1070 gpu
Hi, I just got this thing working and after I connect the client and server correctly and have an app open (tried with Vivecraft and SteamVR Home), the phone screen just says "Connected! Streaming will begin soon." and doesn't do anything. According to the server window, it's sending video information just fine. I'm not sure how to fix this.

**Comment by polygraphene** [comment]
Did try ping from S8 to PC?

**Comment by TrumX** [comment]
Hi!

So today I set up my oculus go with ALVR. after some work on ports etc it worked after changing codec to 264 since Im using an AMD R290oc.

Im doing it via 5ghz wlan, ethernet to box etc.
strange thing is, I am stuck in that screen too... Interestingly, it worked twice with lowering the resolution to 1024x512 and 1536x768, but to be honest, the quality is underwhelming then. 

even on 2880x1440 i have no packet loss, sound gets delivered to my headset and tracking works etc since if I mirror my screen to desktop i can browse through the steam store. headtracking included working. 

but still in that fricking "streaming will begin soon" stream.

any ideas?
